// eslint.config.js
import js from '@eslint/js';
import react from 'eslint-plugin-react';
import prettier from 'eslint-plugin-prettier';
import importPlugin from 'eslint-plugin-import';
import typescriptPlugin from '@typescript-eslint/eslint-plugin';
import globals from 'globals';
import jest from 'eslint-plugin-jest';
import vitest from 'eslint-plugin-vitest';
import sortKeysFix from 'eslint-plugin-sort-keys-fix';
import tsParser from '@typescript-eslint/parser';

export default [
  js.configs.recommended,
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'src/theme/**',
      'package-lock.json',
    ],
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaFeatures: { jsx: true },
        ecmaVersion: 2020,
        sourceType: 'module',
      },
      globals: {
        ...globals.browser,
        ...globals.es2020,
        'jest/globals': true,
        JSX: true,
        ...vitest.environments.env.globals,
      },
    },
    plugins: {
      react,
      '@typescript-eslint': typescriptPlugin,
      prettier,
      import: importPlugin,
      cypress,
      jest,
      'sort-keys-fix': sortKeysFix,
    },
    settings: {
      'import/extensions': ['.js', '.jsx', '.ts', '.tsx'],
      'import/parsers': {
        '@typescript-eslint/parser': ['.ts', '.tsx'],
      },
      'import/resolver': {
        node: {
          extensions: ['.js', '.jsx', '.ts', '.tsx'],
          paths: ['src'],
        },
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', ignoreRestSiblings: true },
      ],
      '@typescript-eslint/no-useless-constructor': 'warn',
      'prettier/prettier': [
        'warn',
        { singleQuote: true, arrowParens: 'avoid' },
      ],
      'no-unused-vars': 'off',
      'no-undef': ['warn'],
      'require-await': 'warn',
      'react/jsx-uses-react': 'off',
      'react/react-in-jsx-scope': 'off',
      'react/no-array-index-key': 'warn',
      'react/jsx-sort-props': 'warn',
      'import/no-extraneous-dependencies': ['warn', { devDependencies: true }],
      'import/no-unresolved': [
        'warn',
        { caseSensitive: false, ignore: ['vitest'] },
      ],
      'no-console': ['warn', { allow: ['warn'] }],
      'sort-keys-fix/sort-keys-fix': [
        'warn',
        'asc',
        { caseSensitive: true, natural: false },
      ],
      'no-use-before-define': 'off',
      '@typescript-eslint/no-use-before-define': 'warn',
      'import/extensions': 'off',
      'react/prop-types': 'off',
      camelcase: 'off',
      'react/require-default-props': 'off',
      'react-hooks/exhaustive-deps': 'off',
      'react/jsx-props-no-spreading': 'off',
      'react/no-unescaped-entities': 'off',
      '@typescript-eslint/camelcase': 'off',
      'react/jsx-filename-extension': [
        'off',
        { extensions: ['.js', '.jsx', '.ts', '.tsx'] },
      ],
      'no-shadow': 'off',
      'no-unused-expressions': 'off',
      'react/jsx-no-bind': 'off',
      'no-param-reassign': 'off',
      'import/prefer-default-export': 'off',
      'no-prototype-builtins': 'off',
      'consistent-return': 'off',
      'jsx-a11y/click-events-have-key-events': 'off',
      'react/no-unused-prop-types': 'off',
      'no-underscore-dangle': 'off',
      'no-restricted-syntax': 'off',
      'jsx-a11y/label-has-associated-control': 'off',
      'jsx-a11y/no-static-element-interactions': 'off',
      'react/button-has-type': 'off',
      'react/destructuring-assignment': 'off',
      'import/no-cycle': 'off',
      '@typescript-eslint/ban-types': 'off',
      'no-nested-ternary': 'off',
      'no-return-assign': 'off',
      'no-return-await': 'off',
      'react/no-children-prop': 'off',
      'jsx-a11y/control-has-associated-label': 'off',
      'jsx-a11y/anchor-is-valid': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/no-empty-interface': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      'array-callback-return': 'off',
      'no-plusplus': 'off',
      'import/export': 'off',
      'react/jsx-key': 'off',
      'react/display-name': 'off',
      'no-restricted-properties': 'off',
      'no-restricted-globals': 'off',
      'jsx-a11y/no-noninteractive-element-interactions': 'off',
      'no-empty': 'off',
      'guard-for-in': 'off',
      eqeqeq: 'off',
      'default-case': 'off',
      'prefer-spread': 'off',
      'import/no-named-as-default': 'off',
      'no-global-assign': 'off',
      radix: 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      'import/newline-after-import': 'off',
      '@typescript-eslint/no-inferrable-types': 'off',
      'import/order': 'off',
      'no-unneeded-ternary': 'off',
      'prefer-const': 'off',
      'react/jsx-curly-brace-presence': 'off',
      'react-hooks/rules-of-hooks': 'off',
      'prefer-template': 'off',
      'react/function-component-definition': 'off',
      'testing-library/prefer-screen-queries': 'off',
      'jest/no-mocks-import': 'off',
      'react/jsx-no-useless-fragment': 'off',
      'testing-library/prefer-find-by': 'off',
      'react/jsx-no-constructed-context-values': 'off',
      'no-unsafe-optional-chaining': 'off',
      'testing-library/prefer-presence-queries': 'off',
      'jest/no-identical-title': 'off',
      'react/no-unstable-nested-components': 'off',
      'testing-library/no-dom-import': 'off',
      'jest/valid-expect': 'off',
      'default-param-last': 'off',
      'testing-library/no-wait-for-snapshot': 'off',
      'testing-library/no-unnecessary-act': 'off',
      'testing-library/no-node-access': 'off',
      'testing-library/no-debugging-utils': 'off',
      'testing-library/no-container': 'off',
      'jest/no-conditional-expect': 'off',
      'testing-library/no-wait-for-side-effects': 'off',
      'testing-library/no-wait-for-multiple-assertions': 'off',
      'testing-library/await-async-query': 'off',
      'no-promise-executor-return': 'off',
      'testing-library/render-result-naming-convention': 'off',
      'prefer-regex-literals': 'off',
      'prefer-exponentiation-operator': 'off',
      'testing-library/no-render-in-setup': 'off',
      'testing-library/no-await-sync-query': 'off',
      'testing-library/await-async-utils': 'off',
      'react/jsx-boolean-value': 'off',
      '@typescript-eslint/no-loss-of-precision': 'off',
      'no-restricted-exports': 'off',
      'no-empty-pattern': 'off',
      'import/no-named-default': 'off',
    },
  },
];
